version: '2.3'

services:
  conductor-server:
    environment:
      - CONFIG_PROP=config.properties
      - db=redis
      - workflow_dynomite_cluster_hosts=redis1:6379:us-east-1c
      - workflow_elasticsearch_url=http://es:9200
      - workflow_elasticsearch_cluster_health_color=yellow
    image: conductor:server
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    networks:
      - internal
    ports:
      - 8080:8080
    links:
      - elasticsearch:es
      - redis:redis1
    healthcheck:
      test: timeout -t 5 sh -c 'nc -z localhost 8080'
      interval: 5s
      timeout: 5s
      retries: 12
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy

  conductor-ui:
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    image: conductor:ui
    build:
      context: ../
      dockerfile: docker/ui/Dockerfile
    networks:
      - internal
    ports:
      - 5000:5000
    links:
      - conductor-server
    healthcheck:
      test: timeout -t 5 sh -c 'nc -z localhost 5000'
      interval: 5s
      timeout: 5s
      retries: 12
    depends_on:
      conductor-server:
        condition: service_healthy
  redis:
    image: redis:5.0-alpine
    ports:
      - 6379:6379
    networks:
      - internal
    healthcheck:
      test: timeout -t 5 sh -c 'nc -z localhost 6379'
      interval: 5s
      timeout: 5s
      retries: 12

  # https://www.elastic.co/guide/en/elasticsearch/reference/6.5/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - internal
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9200'
      interval: 5s
      timeout: 5s
      retries: 12

networks:
  internal:
